build: use a file as flag, stopping indexing until new indexes are consumed
- when running on the same server, once new indexes are rotated to data/cur, the local search server has to be notified
- the file data/cur/UPDATE_READY can be copied over remote servers and used to detect the need to restart search server
- $SEARCH_HOME/is_search_server is another flag file, indicating the current server is also a search server

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -49,81 +49,90 @@ FREEDB_BUILD_FORCE="$SEARCH_HOME/freedb_build_force"
 # if cur isn't a symlink, we run once to prepare the dirs and links
 [ ! -L data/cur ] && (cd data && $SEARCH_HOME/bin/safe_dir_rotation)
 
-echo "Clean up old files"
-! rm -rf data/new/*
+READYFILE="$SEARCH_HOME/data/cur/UPDATE_READY"
 
-run_and_show_errors() {
-	echo "Running $@"
-	if ! "$@"
-	then
-		RC=$?
-		echo "FAIL '$@' (rc=$RC)"
-		return 1
-	else
-		echo "PASS '$@'"
+if [ ! -e "$READYFILE" ]; then
+
+	echo "Clean up old files"
+	! rm -rf data/new/*
+
+	run_and_show_errors() {
+		echo "Running $@"
+		if ! "$@"
+		then
+			RC=$?
+			echo "FAIL '$@' (rc=$RC)"
+			return 1
+		else
+			echo "PASS '$@'"
+			return 0
+		fi
+	}
+
+	build_freedb_index() {
+		if [ -f "$FREEDB_BUILD_FORCE" ]; then
+			echo "Building freedb index (forced)"
+			rm -f "$FREEDB_BUILD_FORCE"
+			return 0
+		fi
+		if [ "$FREEDB_ELAPSED" -lt "$SEARCH_FREEDB_THRESHOLD" ]; then
+			echo "Not building freedb index ($FREEDB_ELAPSED of $SEARCH_FREEDB_THRESHOLD seconds since last freedb build)."
+			return 1
+		fi
+		if [ "$DAY" -ne "$SEARCH_FREEDB_DAY" ]; then
+			echo "Not building freedb index (only on day $SEARCH_FREEDB_DAY)."
+			return 1
+		fi
+		if [ "$HOUR" -lt "$SEARCH_FREEDB_HOUR" ] || [ "$HOUR" -gt "$SEARCH_FREEDB_MAX_HOUR" ]; then
+			echo "Not building freedb index (only between $SEARCH_FREEDB_HOUR and $SEARCH_FREEDB_MAX_HOUR hours)."
+			return 1
+		fi
+		echo "Building freedb index. Last index was started $FREEDB_ELAPSED seconds ago"
 		return 0
-	fi
-}
+	}
 
-build_freedb_index() {
-	if [ -f "$FREEDB_BUILD_FORCE" ]; then
-		echo "Building freedb index (forced)"
-		rm -f "$FREEDB_BUILD_FORCE"
+	if build_freedb_index; then
+		START=$(date +%s)
+		run_and_show_errors make freedb || exit 2
+		echo "$START" > $FREEDB_TIMESTAMP_FILE
+	fi
+
+	build_recording_index() {
+		if [ -f "$REC_BUILD_FORCE" ]; then
+			echo "Building recording index (forced)"
+			rm -f "$REC_BUILD_FORCE"
+			return 0
+		fi
+		if [ "$REC_ELAPSED" -lt "$SEARCH_REC_THRESHOLD" ]; then
+			echo "Not building recording index ($REC_ELAPSED of $SEARCH_REC_THRESHOLD seconds since last recording build)."
+			return 1
+		fi
+		if [ "$HOUR" -lt "$SEARCH_REC_HOUR" ] || [ "$HOUR" -gt "$SEARCH_REC_MAX_HOUR" ]; then
+			echo "Not building recording index (only between $SEARCH_REC_HOUR and $SEARCH_REC_MAX_HOUR hours)."
+			return 1
+		fi
+		echo "Building recording index. Last index was started $REC_ELAPSED seconds ago"
 		return 0
-	fi
-	if [ "$FREEDB_ELAPSED" -lt "$SEARCH_FREEDB_THRESHOLD" ]; then
-		echo "Not building freedb index ($FREEDB_ELAPSED of $SEARCH_FREEDB_THRESHOLD seconds since last freedb build)."
-		return 1
-	fi
-	if [ "$DAY" -ne "$SEARCH_FREEDB_DAY" ]; then
-		echo "Not building freedb index (only on day $SEARCH_FREEDB_DAY)."
-		return 1
-	fi
-	if [ "$HOUR" -lt "$SEARCH_FREEDB_HOUR" ] || [ "$HOUR" -gt "$SEARCH_FREEDB_MAX_HOUR" ]; then
-		echo "Not building freedb index (only between $SEARCH_FREEDB_HOUR and $SEARCH_FREEDB_MAX_HOUR hours)."
-		return 1
-	fi
-	echo "Building freedb index. Last index was started $FREEDB_ELAPSED seconds ago"
-	return 0
-}
+	}
 
-if build_freedb_index; then
-	START=$(date +%s)
-	run_and_show_errors make freedb || exit 2
-	echo "$START" > $FREEDB_TIMESTAMP_FILE
+	if build_recording_index; then
+		START=$(date +%s)
+		run_and_show_errors make recording || exit 2
+		echo "$START" > $REC_TIMESTAMP_FILE
+	fi
+
+	run_and_show_errors make || exit 2
+
+	echo "Rotate generated indexes"
+	(cd data && safe_dir_rotation) || exit 1
+
+	touch $READYFILE
+else
+	echo "Skipping build indexes because $READYFILE exists."
 fi
-
-build_recording_index() {
-	if [ -f "$REC_BUILD_FORCE" ]; then
-		echo "Building recording index (forced)"
-		rm -f "$REC_BUILD_FORCE"
-		return 0
-	fi
-	if [ "$REC_ELAPSED" -lt "$SEARCH_REC_THRESHOLD" ]; then
-		echo "Not building recording index ($REC_ELAPSED of $SEARCH_REC_THRESHOLD seconds since last recording build)."
-		return 1
-	fi
-	if [ "$HOUR" -lt "$SEARCH_REC_HOUR" ] || [ "$HOUR" -gt "$SEARCH_REC_MAX_HOUR" ]; then
-		echo "Not building recording index (only between $SEARCH_REC_HOUR and $SEARCH_REC_MAX_HOUR hours)."
-		return 1
-	fi
-	echo "Building recording index. Last index was started $REC_ELAPSED seconds ago"
-	return 0
-}
-
-if build_recording_index; then
-	START=$(date +%s)
-	run_and_show_errors make recording || exit 2
-	echo "$START" > $REC_TIMESTAMP_FILE
-fi
-
-run_and_show_errors make || exit 2
-
-echo "Rotate generated indexes"
-(cd data && safe_dir_rotation) || exit 1
-
 
 if [ ! -z "$SEARCH_PUSH_TO" ]; then
+	echo "Pushing to remote search servers"
 	for h in $SEARCH_PUSH_TO
 	do
 		SERVER="$h.localdomain"
@@ -137,6 +146,14 @@ if [ ! -z "$SEARCH_PUSH_TO" ]; then
 		fi
 	done
 fi
+
+# if the indexer server is also a search server
+if [ -e "$SEARCH/is_search_server" ]; then
+	echo "Restarting local search server"
+	$SEARCH_HOME/bin/restart_search_server
+fi
+
+rm -f $READYFILE || echo "Failed to remove $READYFILE"
 
 echo "$0 completed"
 
